# Generated by Django 5.2.4 on 2026-06-01 14:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('console', models.CharField(choices=[('NES', 'NES'), ('SNES', 'SNES'), ('N64', 'N64'), ('PS1', 'PlayStation 1'), ('GB', 'Game Boy')], max_length=10)),
                ('genre', models.CharField(choices=[('action', 'Action'), ('rpg', 'RPG'), ('sports', 'Sports'), ('puzzle', 'Puzzle'), ('platformer', 'Platformer'), ('racing', 'Racing')], max_length=20)),
                ('description', models.TextField(blank=True)),
                ('cover_image', models.ImageField(upload_to='games/')),
            ],
        ),
        migrations.CreateModel(
            name='GradedItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.CharField(choices=[('10.0', 'Mint 10.0'), ('9.8', '9.8'), ('9.6', '9.6'), ('9.4', '9.4'), ('9.2', '9.2'), ('9.0', '9.0')], max_length=5)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('stock', models.PositiveIntegerField(default=1)),
                ('is_available', models.BooleanField(default=True)),
                ('slab_image', models.ImageField(upload_to='graded_items/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='graded_items', to='store.game')),
            ],
        ),
    ]
