# Generated by Django 5.2.4 on 2026-06-01 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='console',
            field=models.CharField(choices=[('NES', 'NES'), ('SNES', 'SNES'), ('N64', 'N64'), ('PS1', 'PlayStation 1'), ('GB', 'Game Boy'), ('XBOX', 'Xbox')], max_length=10),
        ),
    ]
