# Generated by Django 5.2.4 on 2026-06-02 10:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_alter_game_console'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gradeditem',
            name='stock',
        ),
    ]
